### ISSUE TITLE
Angular 2.0.0 Final: core_1.provide is not a function

### ISSUE THREAD

**Issue by YvesCandel** [alenny/angular2-adal#14] opened 2016-09-16 07:44 UTC
Getting stuck on the following error using the Angular2 Final version:

Error: TypeError: core_1.provide is not a function
        at Object.eval (http://localhost:5555/node_modules/angular2-adal/core.js:15:12)
        at eval (http://localhost:5555/node_modules/angular2-adal/core.js:20:4)
        at eval (http://localhost:5555/node_modules/angular2-adal/core.js:21:3)
        at Object.eval (http://localhost:5555/app/shared/trip/trip.service.js:15:14)
    Evaluating http://localhost:5555/node_modules/angular2-adal/core.js
    Evaluating http://localhost:5555/app/shared/trip/trip.service.js
    Evaluating http://localhost:5555/app/shared/trip/index.js
    Evaluating http://localhost:5555/app/shared/index.js
    Evaluating http://localhost:5555/app/app.component.js
    Evaluating http://localhost:5555/app/app.module.js
    Evaluating http://localhost:5555/app/main.js
    Error loading http://localhost:5555/app/main.js "Report this error at https://github.com/mgechev/angular2-seed/issues"(anonymous function) @ (index):110ZoneDelegate.invoke @ zone.js?1474011477542:192Zone.run @ zone.js?1474011477542:85(anonymous function) @ zone.js?1474011477542:451ZoneDelegate.invokeTask @ zone.js?1474011477542:225Zone.runTask @ zone.js?1474011477542:125drainMicroTaskQueue @ zone.js?1474011477542:357ZoneTask.invoke @ zone.js?1474011477542:297

Anyone got any suggestions?

**Comment by jimontheriver** [comment] 2016-09-23 21:13
I'm having the same issue. There was a change in angular to how dependency injection is handled that may be causing this but I haven't been able to track it down yet in the time I've had. It's possibly in one of the libraries this depends on.

**Comment by cosminpopescu** [comment] 2016-09-30 07:47
I am having the same problem.

**Comment by YvesCandel** [comment] 2016-09-30 11:05
I "fixed" this by simply copying the adal.service.ts and oauthdata.model.ts into my own project rather than fetching them with NPM. You will have to get the "adal-angular" npm module and save it in your project dependencies, and also add the necessary "adal" @types or typings to your project.

Personally I use the angular2-seed project as a base for my solution, and I also added these lines to my seed.config.ts:

```
SYSTEM_CONFIG_DEV: any = {
...
packageConfigPaths: [
     `/node_modules/adal-angular/package.json`,
...
paths: {
     'adal/*': 'node_modules/adal-angular/*',
...
packages: {
      'adal': {
        main: 'adal.js',
        defaultExtension: 'js'
      }
    },
    map: {
      'adal': `${this.APP_BASE}node_modules/adal-angular/lib/adal`
    }
...
SYSTEM_BUILDER_CONFIG: any = {
...
     packageConfigPaths: [
      join(this.PROJECT_ROOT, 'node_modules', 'adal-angular', '*', 'package.json')
...
paths: {
  'adal': {
    main: 'lib/adal.js',
    defaultExtension: 'js'
  }
},
map: {
  'adal': join(this.PROJECT_ROOT, 'node_modules/adal-angular')
}
```

and in my typings.json:

`"adal": "github:DefinitelyTyped/DefinitelyTyped/adal-angular/adal.d.ts#53347571e6f44ed9a961b569bb81893fde4789c1",`

I can now use the the service in all my components:

`import { AdalService } from '../adal/index'; (/index because i made my own index.ts which exports the adal service)`

And in my main app component:

```
constructor(private adalService: AdalService)

adalService.init({
  tenant: 'guid',
  clientId: 'guid',
  endpoints: {'https://websiteurl': 'https://company.onmicrosoft.com/app'},
  cacheLocation: 'localStorage'
});
adalService.handleWindowCallback();
```

This allows you to make a very simple AuthGuard:

```
import { Injectable } from '@angular/core';
import { CanActivate, Router } from '@angular/router';
import { AdalService } from '../adal/index';

@Injectable()
export class AuthGuard implements CanActivate {
  constructor(private adalService: AdalService, private router: Router) {}

  canActivate() {
    if (!this.adalService.userInfo.isAuthenticated) {
      this.adalService.login();
      return false;
    } else {
      console.log('AuthGuard: User is logged in as ' + this.adalService.userInfo.userName);
      return true;
    }
  }
}
```

Hope this helps anyone. It's no solution yet for the problem in this library, but for me it's a workaround until this library (or Microsoft comes with their own Angular2 module) is updated for implementation with Angular2 Final.

**Comment by abhijoseph** [comment] 2016-10-11 23:16
If you use the below construct in core.ts for exporting one of your errors should go away, but I haven't been able to go beyond to fully make use of the library.

```
export const ANGULAR2_ADAL_PROVIDERS: any[] = [
    {
        provide: AdalService,
        useClass: AdalService
    }
];
```

instead of 
`provide(AdalService, {useClass: AdalService})`

**Comment by nelsonmorais** [comment] 2016-10-29 00:25
+1 See also: https://github.com/sureshchahal/angular2-adal/issues/3

**Comment by WhitWaldo** [comment] 2016-10-29 01:18
This is definitely fixed by just recreating the service itself within a project, but I've been looking to figure out what the issue is as well. It's a side-project at this point, but I'm working on it.

It's not necessarily something in the libraries this depends on since it works fine, just apparently not as a separate module for some reason.

**Comment by MikeLallemont** [comment] 2016-11-02 15:15
Anyone have luck using webpack 2 to load the package? I also need to use it in an Ionic 2 project which does not have Angular Router. Also Ionic is using Angular 2.0.0, so it needs to support that.

**Comment by nelsonmorais** [comment] 2016-11-08 23:56
This is now fixed in the ng2-adal, see: https://github.com/sureshchahal/angular2-adal/issues/3

**Comment by fume** [comment] 2016-11-09 07:32
We are also exposing it via NgModules now!!

https://github.com/sureshchahal/angular2-adal/issues/8

**Comment by ranveeraggarwal** [comment] 2017-01-02 17:27
I too had this issue. Here's an example where it's completely fixed. This repo is based on Angular2-Quickstart: https://github.com/ranveeraggarwal/ng2-adal-QuickStart

**Closed as completed** 2017-04-28 12:11 UTC
